name: Azure Web App Container Deployment

 

on:
  push:
    branches:
      - CISetupFeature # Change this to your default branch

 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
